import React from 'react';
import { motion } from 'motion/react';
import { Scale, Shield, FileText, AlertTriangle } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';

export default function LegalView() {
  return (
    <motion.div
      key="legal"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="max-w-4xl mx-auto space-y-8"
    >
      <div className="space-y-4">
        <h1 className="text-3xl font-bold font-display text-foreground">Legal Center</h1>
        <p className="text-muted-foreground">Comprehensive information regarding your usage of Aetheris Ventures.</p>
      </div>

      <div className="space-y-6">
        <Card className="aetheris-card border-none">
          <CardHeader className="flex flex-row items-center gap-2">
            <FileText className="text-primary" />
            <CardTitle>Terms of Service</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-sm text-muted-foreground">
            <p>By accessing Aetheris Ventures, you agree to these legally binding terms. Our services are provided for the purpose of business conceptualization and automation.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Usage Compliance:</strong> You agree not to use the generated content for illegal activities.</li>
              <li><strong>Service Modifications:</strong> We reserve the right to modify or discontinue any feature at any time.</li>
              <li><strong>Account Responsibility:</strong> You are responsible for maintaining the confidentiality of your account credentials.</li>
            </ul>
          </CardContent>
        </Card>

        <Card className="aetheris-card border-none">
          <CardHeader className="flex flex-row items-center gap-2">
            <Shield className="text-accent" />
            <CardTitle>Privacy Policy</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-sm text-muted-foreground">
            <p>Your privacy is paramount. We handle your data with strict protocols and transparency.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Data Collection:</strong> We collect only the data necessary to improve your experience, such as project metrics and preferences.</li>
              <li><strong>AI Processing:</strong> Your inputs are transmitted to AI models (like Google Gemini) to generate business insights. We prioritize not sending personally identifiable information (PII) beyond what is required for your venture details.</li>
              <li><strong>Data Sharing:</strong> We do not sell your personal data.</li>
            </ul>
          </CardContent>
        </Card>
        
        <Card className="aetheris-card border-none">
          <CardHeader className="flex flex-row items-center gap-2">
            <AlertTriangle className="text-amber-500" />
            <CardTitle>Disclaimers & Liability</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-sm text-muted-foreground">
            <p><strong>AI Content Disclaimer:</strong> All business ideas and code generated by Aetheris Ventures are conceptual. Accuracy relies on AI model outputs, which may occasionally contain errors or hallucinations. You must independently verify all content before use.</p>
            <p><strong>Professional Advice:</strong> Aetheris Ventures does not provide legal, tax, or financial advice. Our simulations do not guarantee business success or financial performance.</p>
            <p><strong>Limitation of Liability:</strong> To the maximum extent permitted by law, Aetheris Ventures shall not be liable for any damages—direct or indirect—arising from your use of this platform or any ventures launched based on our tools.</p>
          </CardContent>
        </Card>
      </div>
    </motion.div>
  );
}
