import React from 'react';
import { motion } from 'motion/react';
import { FileText, Shield, Scale } from 'lucide-react';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { buttonVariants } from '@/components/ui/button';
import { cn } from '@/lib/utils';

export default function LegalView() {
  return (
    <motion.div
      key="legal"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="max-w-4xl mx-auto space-y-8"
    >
      <div className="space-y-4">
        <h1 className="text-3xl font-bold font-display text-foreground">Legal & Compliance</h1>
        <p className="text-muted-foreground">Essential documents and regulatory information for your AI ventures.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Dialog>
          <DialogTrigger nativeButton={true} render={
            <button className={cn(buttonVariants({ variant: 'outline', size: 'default' }), "glass border-none hover:bg-secondary/20 transition-all cursor-pointer w-full text-left flex flex-col items-start p-6 space-y-3 h-auto")}>
              <div className="p-2 w-fit rounded-lg bg-secondary/50">
                <FileText className="text-primary" />
              </div>
              <h4 className="font-bold">Terms of Service</h4>
              <p className="text-xs text-muted-foreground whitespace-normal">Standard operating agreement for Aetheris Ventures and generated ventures.</p>
            </button>
          } />
          <DialogContent className="aetheris-card border-none max-w-2xl">
            <DialogHeader>
              <DialogTitle>Terms of Service</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 text-sm text-muted-foreground">
              <p className="font-bold text-foreground">1. Acceptance of Terms</p>
              <p>By using Aetheris Ventures, you agree to be bound by these terms. This platform provides AI-assisted business generation and automation tools.</p>
              <p className="font-bold text-foreground">2. AI-Generated Content</p>
              <p>All business ideas, prompts, and code are generated by AI. Aetheris Ventures does not guarantee the accuracy, legality, or profitability of any output. Users must review and verify all generated content.</p>
              <p className="font-bold text-foreground">3. Financial Responsibility</p>
              <p>Users are solely responsible for any financial decisions made using this platform. Aetheris Ventures is not a financial advisor.</p>
              <p className="font-bold text-foreground">4. Limitation of Liability</p>
              <p>Aetheris Ventures shall not be liable for any direct, indirect, or consequential damages resulting from the use of the platform or generated businesses.</p>
            </div>
          </DialogContent>
        </Dialog>

        <Dialog>
          <DialogTrigger nativeButton={true} render={
            <button className={cn(buttonVariants({ variant: 'outline', size: 'default' }), "glass border-none hover:bg-secondary/20 transition-all cursor-pointer w-full text-left flex flex-col items-start p-6 space-y-3 h-auto")}>
              <div className="p-2 w-fit rounded-lg bg-secondary/50">
                <Shield className="text-accent" />
              </div>
              <h4 className="font-bold">Privacy Policy</h4>
              <p className="text-xs text-muted-foreground whitespace-normal">How we handle data and protect user privacy across all platforms.</p>
            </button>
          } />
          <DialogContent className="aetheris-card border-none max-w-2xl">
            <DialogHeader>
              <DialogTitle>Privacy Policy</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 text-sm text-muted-foreground">
              <p className="font-bold text-foreground">1. Data Collection</p>
              <p>We collect user profile information (state, name) and project data to provide personalized business tips and track automation progress.</p>
              <p className="font-bold text-foreground">2. AI Processing</p>
              <p>User inputs are processed by third-party AI models (Google Gemini). We do not share PII with these models unless necessary for the business logic requested.</p>
              <p className="font-bold text-foreground">3. Security</p>
              <p>We implement industry-standard security measures to protect your data. However, no system is 100% secure.</p>
            </div>
          </DialogContent>
        </Dialog>

        <Dialog>
          <DialogTrigger nativeButton={true} render={
            <button className={cn(buttonVariants({ variant: 'outline', size: 'default' }), "glass border-none hover:bg-secondary/20 transition-all cursor-pointer w-full text-left flex flex-col items-start p-6 space-y-3 h-auto")}>
              <div className="p-2 w-fit rounded-lg bg-secondary/50">
                <Scale className="text-primary" />
              </div>
              <h4 className="font-bold">Disclaimers</h4>
              <p className="text-xs text-muted-foreground whitespace-normal">Important legal notices regarding AI-generated content and revenue.</p>
            </button>
          } />
          <DialogContent className="aetheris-card border-none max-w-2xl">
            <DialogHeader>
              <DialogTitle>Legal Disclaimers</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 text-sm text-muted-foreground">
              <p className="font-bold text-foreground">No Guarantee of Results</p>
              <p>The "0-capital" business models are conceptual. Success depends on market conditions, user execution, and technical factors beyond our control.</p>
              <p className="font-bold text-foreground">Not Legal Advice</p>
              <p>State-specific tips are for informational purposes only and do not constitute legal or tax advice. Consult with a qualified professional in your jurisdiction.</p>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      <Card className="aetheris-card border-none">
        <CardHeader>
          <CardTitle className="text-foreground">Comprehensive Disclaimer</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground space-y-4">
          <p>Aetheris Ventures is a tool for generating business concepts and automating certain technical tasks. We do not guarantee revenue, success, or legal compliance of any generated business. Users are responsible for verifying all AI-generated code, content, and business strategies.</p>
          <p>Financial projections are simulations and do not represent guaranteed earnings. Always consult with legal and financial professionals before launching a business venture.</p>
        </CardContent>
      </Card>
    </motion.div>
  );
}
